CREATE DATABASE clinic;

CREATE TABLE patients (
  id              INT  PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name            VARCHAR(100) NOT NULL,
  date_of_birth   DATE NOT NULL
);

CREATE TABLE medical_histories (
  id              INT  PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  admitted_at     TIMESTAMP,
  patient_id      INT,
  FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  status          VARCHAR(100) NOT NULL);

CREATE TABLE treatments (
  id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type            VARCHAR(100)    NOT NULL,
  name            VARCHAR(100)    NOT NULL
);
